### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yofukashino** [D3SOX/powercord-yt-embed-fix#2]
`The media could not be loaded, either because the server or network failed or because the format is not supported.`
this is the error i get when trying to play an video

**Comment by D3SOX** [comment]
Did you change the instance? If yes to which one?
And with which video did that happen?

Still works fine for me.

**Comment by yofukashino** [comment]
[This video.](https://www.youtube.com/watch?v=EX_8ZjT2sO4 ) and no I didn't change

**Comment by D3SOX** [comment]
Oh, that's because that video is age-restricted and invidious can't bypass it right now

**Comment by yofukashino** [comment]
sad
