### ISSUE TITLE
Better discord port. 

### ISSUE THREAD

**Issue by yofukashino** [D3SOX/powercord-yt-embed-fix#3]
Well I have made it
So can I release it? If yes. Then what credits?

**Comment by D3SOX** [comment]
Feel free to open a PR :smile:

**Comment by yofukashino** [comment]
Nah I will publish it in my repo with a link of your repo as credits

**Comment by D3SOX** [comment]
Ok go ahead. Just link this repo as a source and I'll add a link to yours in my `README` for BetterDiscord users

**Comment by yofukashino** [comment]
thanks

**Comment by yofukashino** [comment]
will notify you after uploading it

**Comment by yofukashino** [comment]
https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/BypassYoutubeEmbedRestriction.plugin.js
